<a href="https://colab.research.google.com/github/Mountain-Biker/pydata-book-practice/blob/main/chapter5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Chapter 5. Getting Started with pandas

In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

## 5.1 Introduction to pandas Data Structures

### Series

A Series is a one-dimensional array-like object containing a sequence of values of the same type and an associated array of data labels, called its index.

In [8]:
obj = pd.Series([4, 5, -7, 3])

In [9]:
obj

0    4
1    5
2   -7
3    3
dtype: int64

In [10]:
obj2 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])

In [11]:
obj2

a    1
b    2
c    3
d    4
dtype: int64

In [12]:
obj2.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [13]:
obj2['a']

1

In [14]:
obj2['b'] = 6

In [16]:
obj2[['a', 'b']] = -1

In [17]:
obj2

a   -1
b   -1
c    3
d    4
dtype: int64

Using Numpy functions or Numpy-like operations, such as filtering with a Boolean array, scalar multiplication, or applying math functions, will preserve the index-value relationship.

In [18]:
obj2[obj2 > 0]

c    3
d    4
dtype: int64

In [19]:
obj2 * 2

a   -2
b   -2
c    6
d    8
dtype: int64

In [21]:
np.exp(obj2)

a     0.367879
b     0.367879
c    20.085537
d    54.598150
dtype: float64

Another way to think about a Series is as a **fixed-length, ordered dictionary**, as it is a mapping of index values to data values. It can be used in many context where you might use a dictionary.

In [22]:
'b' in obj2

True

In [23]:
'e' in obj2

False

A series can be created from a dictionary.

In [25]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

A series can be converted back to a dictionary with its to_dict method.

In [26]:
obj3.to_dict()

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [27]:
states = ['California', 'Utah', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)

In [28]:
obj4

California        NaN
Utah           5000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

The isna and notna functions in pandas should be used to detect missing data.

In [29]:
pd.isna(obj4)

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

In [30]:
obj4.isna()

California     True
Utah          False
Oregon        False
Texas         False
dtype: bool

A useful Series feature for many applications is that it automatically aligns by index label in arithmetic operations:

In [31]:
obj3 + obj4

California         NaN
Ohio               NaN
Oregon         32000.0
Texas         142000.0
Utah           10000.0
dtype: float64

### DataFrame